// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddReactionReducer from "./add_reaction_reducer";
import CreateDmReducer from "./create_dm_reducer";
import CreateRoomReducer from "./create_room_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import EditMessageReducer from "./edit_message_reducer";
import JoinRoomReducer from "./join_room_reducer";
import LeaveRoomReducer from "./leave_room_reducer";
import MarkReadReducer from "./mark_read_reducer";
import RemoveReactionReducer from "./remove_reaction_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetNameReducer from "./set_name_reducer";
import SetTypingReducer from "./set_typing_reducer";
import UpdateProfileReducer from "./update_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import MessageRow from "./message_table";
import ReactionRow from "./reaction_table";
import RoomRow from "./room_table";
import RoomMemberRow from "./room_member_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  message: __table({
    name: 'message',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'roomId', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { name: 'sender', algorithm: 'btree', columns: [
        'sender',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  reaction: __table({
    name: 'reaction',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'messageId', algorithm: 'btree', columns: [
        'messageId',
      ] },
    ],
    constraints: [
      { name: 'reaction_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ReactionRow),
  room: __table({
    name: 'room',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'room_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomRow),
  room_member: __table({
    name: 'room_member',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'roomId', algorithm: 'btree', columns: [
        'roomId',
      ] },
      { name: 'userId', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'room_member_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RoomMemberRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_reaction", AddReactionReducer),
  __reducerSchema("create_dm", CreateDmReducer),
  __reducerSchema("create_room", CreateRoomReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("join_room", JoinRoomReducer),
  __reducerSchema("leave_room", LeaveRoomReducer),
  __reducerSchema("mark_read", MarkReadReducer),
  __reducerSchema("remove_reaction", RemoveReactionReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_name", SetNameReducer),
  __reducerSchema("set_typing", SetTypingReducer),
  __reducerSchema("update_profile", UpdateProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

