// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  sender: __t.identity(),
  sent: __t.timestamp(),
  text: __t.string(),
  editedAt: __t.option(__t.timestamp()).name("edited_at"),
  replyToId: __t.option(__t.u64()).name("reply_to_id"),
  imageUrl: __t.option(__t.string()).name("image_url"),
});
