// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddReactionReducer from "../add_reaction_reducer";
import CreateDmReducer from "../create_dm_reducer";
import CreateRoomReducer from "../create_room_reducer";
import DeleteMessageReducer from "../delete_message_reducer";
import EditMessageReducer from "../edit_message_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import MarkReadReducer from "../mark_read_reducer";
import RemoveReactionReducer from "../remove_reaction_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetNameReducer from "../set_name_reducer";
import SetTypingReducer from "../set_typing_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type AddReactionParams = __Infer<typeof AddReactionReducer>;
export type CreateDmParams = __Infer<typeof CreateDmReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DeleteMessageParams = __Infer<typeof DeleteMessageReducer>;
export type EditMessageParams = __Infer<typeof EditMessageReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type MarkReadParams = __Infer<typeof MarkReadReducer>;
export type RemoveReactionParams = __Infer<typeof RemoveReactionReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetTypingParams = __Infer<typeof SetTypingReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

